[pytest]

addopts = -v -s --alluredir=reports/allure-results

testpaths = tests

log_cli = true
log_cli_level = INFO

markers =
    smoke: critical tests
    regression: full suite
    api: api tests
    ui: ui tests
    hybrid: hybrid tests