name: Selenium E2E Tests

permissions:
  contents: write

env:
  BASE_URL: ${{ secrets.BASE_URL }}
  TEST_USERNAME: ${{ secrets.USERNAME }}
  TEST_PASSWORD: ${{ secrets.PASSWORD }}
  HEADLESS: true
  BROWSER: chrome

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [chrome, firefox]

    env:
      BASE_URL: ${{ secrets.BASE_URL }}
      TEST_USERNAME: ${{ secrets.USERNAME }}
      TEST_PASSWORD: ${{ secrets.PASSWORD }}
      HEADLESS: true
      BROWSER: ${{ matrix.browser }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest-xdist pytest-html pytest-rerunfailures

      - name: Install Chrome
        if: matrix.browser == 'chrome'
        uses: browser-actions/setup-chrome@v1

      - name: Install Firefox
        if: matrix.browser == 'firefox'
        uses: browser-actions/setup-firefox@v1

      - name: Create folders
        run: mkdir -p reports logs screenshots

      - name: Run tests
        run: |
          pytest -n 2 --html=reports/report-${{ matrix.browser }}.html --self-contained-html

      - name: Upload report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: report-${{ matrix.browser }}
          path: reports/

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: logs-${{ matrix.browser }}
          path: logs/

      - name: Upload screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots-${{ matrix.browser }}
          path: screenshots/